# Generated by Django 4.2.7 on 2023-12-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=50, verbose_name='Task Title:')),
                ('taskDescription', models.TextField(verbose_name='Task Description:')),
                ('completed', models.BooleanField(default=False, verbose_name='Task Completed:')),
                ('date', models.DateTimeField(default='12/10/2023', verbose_name='Date:')),
                ('categories', models.ManyToManyField(to='categories.category')),
            ],
        ),
    ]
