# Generated by Django 4.2.7 on 2023-12-10 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 12, 56, 5, 797303)),
        ),
    ]
